require.config({
    paths: {
        'modernizr':   'components/modernizr/modernizr',
        'bootstrap':   'components/bootstrap/docs/assets/js/bootstrap',
        'domReady':    'components/requirejs-domready/domReady',
        'hoverIntent': '/++resource++collective.collage.megamenu/jquery.hoverIntent.minified',
        'collage':     '/++resource++collage-resources/collage',
        'collage-patch': '/++resource++collective.collage.megamenu/collage-patch',
        'megamenu':    '/++resource++collective.collage.megamenu/megamenu',
        'jquery-integration': '/jquery-integration',
        'jquerytools': '/++resource++plone.app.jquerytools',
        'jquerytools-dateinput': '/++resource++plone.app.jquerytools.dateinput',
        'jquerytools-overlayhelpers': '/++resource++plone.app.jquerytools.overlayhelpers',
        'jquerytools-form': '/++resource++plone.app.jquerytools.form',
        'register-function': '/register_function',
        'plone_javascript_variables': '/plone_javascript_variables',
        'nodeutilities': '/nodeutilities',
        'cookie_functions': '/cookie_functions',
        'livesearch': '/livesearch',
        'search': '/++resource++search',
        'select_all': '/select_all',
        'dragdropreorder': '/dragdropreorder',
        'collapsiblesections': '/collapsiblesections',
        'form_tabbing': '/form_tabbing',
        'popupforms': '/popupforms',
        'jquery.highlightsearchterms': '/jquery.highlightsearchterms',
        'first_input_focus': '/first_input_focus',
        'accessibility': '/accessibility',
        'styleswitcher': '/styleswitcher',
        'toc': '/toc',
        'collapsibleformfields': '/collapsibleformfields',
        'comments': '/++resource++plone.app.discussion.javascripts/comments',
        'dropdown': '/dropdown',
        'table_sorter': '/table_sorter',
        'calendar_formfield': '/calendar_formfield',
        'formUnload': '/formUnload',
        'formsubmithelpers': '/formsubmithelpers',
        'unlockOnFormUnload': '/unlockOnFormUnload',
        'autocomplete': '/++resource++plone.formwidget.autocomplete/jquery.autocomplete.min',
        'formwidget-autocomplete': '/++resource++plone.formwidget.autocomplete/formwidget-autocomplete',
        'contenttree': '/++resource++plone.formwidget.contenttree/contenttree',
        'jquery_prettyPhoto': '/++resource++jquery.prettyPhoto',
        'prettyPhoto': '/prettyPhoto',
        'login': '/login',
        'domready_script': 'js/scripts',
        'eea_tags': '++resource++eea.tags',
        'tokeninput': '++resource++jquery.tokeninput',
        'mark_special': 'mark_special_links',
        'carousel': '++resource++carousel',
        'flowplayer': '++resource++collective.flowplayer/flowplayer.min',
        'flowplayer_playlist': '++resource++collective.flowplayer/flowplayer.playlist.min',
        'collective_flowplayer': 'collective.flowplayer',
        'nivoslider': '++resource++jquery.nivo.slider.pack',
        'ptg_portlet': '++resource++plonetruegallery-portlet',
        'mybookmarks': '++resource++collective.portlet.mybookmarks.javascripts/addExternalBookmark',
        'mybookmarks_hiddenStructure': '++resource++collective.portlet.mybookmarks.javascripts/setHiddenStructure',

        'jquery.ui': '++resource++jquery-ui/jquery.ui.core.min',
        'jquery.ui.wiget': '++resource++jquery-ui/jquery.ui.widget.min',
        'jquery.ui.mouse': '++resource++jquery-ui/jquery.ui.mouse.min',
        'jquery.ui.position': '++resource++jquery-ui/jquery.ui.position.min',
        'jquery.ui.draggable': '++resource++jquery-ui/jquery.ui.draggable.min',
        'jquery.ui.droppable': '++resource++jquery-ui/jquery.ui.droppable.min',
        'jquery.ui.resizable': '++resource++jquery-ui/jquery.ui.resizable.min',
        'jquery.ui.selectable': '++resource++jquery-ui/jquery.ui.selectable.min',
        'jquery.ui.sortable': '++resource++jquery-ui/jquery.ui.sortable.min',
        'jquery.ui.accordion': '++resource++jquery-ui/jquery.ui.accordion.min',
        'jquery.ui.autocomplete': '++resource++jquery-ui/jquery.ui.autocomplete.min',
        'jquery.ui.button': '++resource++jquery-ui/jquery.ui.button.min',
        'jquery.ui.dialog': '++resource++jquery-ui/jquery.ui.dialog.min',
        'jquery.ui.slider': '++resource++jquery-ui/jquery.ui.slider.min',
        'jquery.ui.tabs': '++resource++jquery-ui/jquery.ui.tabs.min',
        'jquery.ui.datepicker': '++resource++jquery-ui/jquery.ui.datepicker.min',
        'jquery.ui.progressbar': '++resource++jquery-ui/jquery.ui.progressbar.min',
        'fullcalendar': '++resource++collective.js.fullcalendar/fullcalendar.min',
        'fullcalendar.gcal': '++resource++collective.js.fullcalendar/fullcalendar.gcal',
        'jquery.twitter': '++resource++jquery.twitter',
        'solgema_context': 'solgema_contextualcontentmenu',
        'colorpicker_eye': '++resource++collective.js.colorpicker.js/eye',
        'colorpicker_utils': '++resource++collective.js.colorpicker.js/utils',
        'colorpicker': '++resource++collective.js.colorpicker.js/colorpicker',
        'twothumbs': '++resource++cioppino.twothumbs.javascripts/twothumbs',
        'ploneglossary': 'ploneglossary',
        'ploneglossary_definitions': 'ploneglossary_definitions',
        'quickupload_swfobject': '++resource++quickupload_static/swfobject',
        'quickupload_uploadify': '++resource++quickupload_static/jquery.uploadify',
        'quickupload_fileuploader': '++resource++quickupload_static/fileuploader',
        'quickupload_helpers': '++resource++quickupload_static/helpers',
        'easySlider': '++resource++easySlider',
        'easySlider_portlet': '++resource++easyslider-portlet',
        'easySlider_settings': '++resource++slider-settings',



      },

    shim: {
        'jquerytools-dateinput': ['jquerytools'],
        'jquerytools-overlayhelpers': ['jquerytools'],
        'jquerytools-form': ['jquerytools'],
        'search': ['modernizr','plone_javascript_variables'],
        'select_all': ['plone_javascript_variables'],
        'popupforms': ['jquerytools-overlayhelpers'],
        'accessibility': ['cookie_functions'],
        'styleswitcher': ['cookie_functions'],
        'formwidget-autocomplete': ['autocomplete'],
        'prettyPhoto': ['jquery_prettyPhoto'],
        'collage-patch': ['collage'],
        'hoverIntent': ['collage', 'collage-patch'],
        'megamenu': ['hoverIntent'],
        'login': ['register-function'],
        'domready_script': ['megamenu', 'domReady'],
    }
});
require([
    'domReady',
    'jquery-integration',
    'jquerytools',
    'jquerytools-dateinput',
    'jquerytools-overlayhelpers',
    'jquerytools-form',
    'register-function',
    'plone_javascript_variables',
    'nodeutilities',
    'cookie_functions',
    'livesearch',
    'search',
    'select_all',
    'dragdropreorder',
    'collapsiblesections',
    'form_tabbing',
    'popupforms',
    'jquery.highlightsearchterms',
    'first_input_focus',
    'accessibility',
    'styleswitcher',
    'toc',
    'collapsibleformfields',
    'comments',
    'dropdown',
    'table_sorter',
    'calendar_formfield',
    'formUnload', 
    'formsubmithelpers',
    'unlockOnFormUnload',
    'autocomplete',
    'formwidget-autocomplete',
    'contenttree',
    'jquery_prettyPhoto',
    'prettyPhoto',
    'collage',
    'collage-patch',
    'hoverIntent',
    'megamenu',
    'bootstrap',
    'login',
    'domready_script',
    'eea_tags',
    'tokeninput',
    'mark_special',
    'carousel',
    'flowplayer',
    'flowplayer_playlist',
    'collective_flowplayer',
    'nivoslider',
    'ptg_portlet',
    'mybookmarks',
    'mybookmarks_hiddenStructure',
    'jquery.ui',
    'jquery.ui.wiget',
    'jquery.ui.mouse',
    'jquery.ui.position',
    'jquery.ui.draggable',
    'jquery.ui.droppable',
    'jquery.ui.resizable',
    'jquery.ui.selectable',
    'jquery.ui.sortable',
    'jquery.ui.accordion',
    'jquery.ui.autocomplete',
    'jquery.ui.button',
    'jquery.ui.dialog',
    'jquery.ui.slider',
    'jquery.ui.tabs',
    'jquery.ui.datepicker',
    'jquery.ui.progressbar',
    'fullcalendar',
    'fullcalendar.gcal',
    'jquery.twitter',
    'solgema_context',
    'colorpicker_eye',
    'colorpicker_utils',
    'colorpicker',
    'twothumbs',
    'ploneglossary',
    'ploneglossary_definitions',
    'quickupload_swfobject',
    'quickupload_uploadify',
    'quickupload_fileuploader',
    'quickupload_helpers',
    'easySlider',
    'easySlider_portlet',
    'easySlider_settings',
], function(domReady){
    domReady(function() {
    });
});
