({                                                                                               
    //appDir: ".",                                                                   
    //baseUrl: "../../../../../../",                                                             
    baseUrl: ".",
    name: "main",
    out: "main-built.js",
    //dir: "./build",                                                       
    //out: "main-built.js",
    //Comment out the optimize line if you want                                      
    //the code minified by UglifyJS                                                  
    //optimize: "none",                                                                

    paths: {
        //'main': './main',
        'jquery': 'empty:',
        'bootstrap':   'components/bootstrap/docs/assets/js/bootstrap',
        'domReady':    'components/requirejs-domready/domReady',
        'hoverIntent': '../../../../../collective.collage.megamenu/collective/collage/megamenu/browser/resources/jquery.hoverIntent.minified',
        'collage':     '../../../../../Products.Collage/Products/Collage/browser/resources/collage',
        'collage-patch': '../../../../../collective.collage.megamenu/collective/collage/megamenu/browser/resources/collage-patch',
        'megamenu':    '../../../../../collective.collage.megamenu/collective/collage/megamenu/browser/resources/megamenu',
        'jquery-integration': '../../../../../../../buildout-cache/eggs/Products.CMFPlone-4.2.1.1-py2.7.egg/Products/CMFPlone/skins/plone_ecmascript/jquery-integration',
        'jquerytools': '../../../../../../../buildout-cache/eggs/plone.app.jquerytools-1.3.2-py2.7.egg/plone/app/jquerytools/browser/jquery.tools.min',
        'jquerytools-dateinput': '../../../../../../../buildout-cache/eggs/plone.app.jquerytools-1.3.2-py2.7.egg/plone/app/jquerytools/browser/jquery.tools.dateinput.min',
        'jquerytools-overlayhelpers': '../../../../../../../buildout-cache/eggs/plone.app.jquerytools-1.3.2-py2.7.egg/plone/app/jquerytools/browser/overlayhelpers',
        'jquerytools-form': '../../../../../../../buildout-cache/eggs/plone.app.jquerytools-1.3.2-py2.7.egg/plone/app/jquerytools/browser/jquery.form.min',
        'register-function': '../../../../../../../buildout-cache/eggs/Products.CMFPlone-4.2.1.1-py2.7.egg/Products/CMFPlone/skins/plone_ecmascript/register_function',
        'plone_javascript_variables': 'empty:',
        'nodeutilities': '../../../../../../../buildout-cache/eggs/Products.CMFPlone-4.2.1.1-py2.7.egg/Products/CMFPlone/skins/plone_ecmascript/nodeutilities',
        'cookie_functions': '../../../../../../../buildout-cache/eggs/Products.CMFPlone-4.2.1.1-py2.7.egg/Products/CMFPlone/skins/plone_ecmascript/cookie_functions',
        'livesearch': '../../../../../../../buildout-cache/eggs/Products.CMFPlone-4.2.1.1-py2.7.egg/Products/CMFPlone/skins/plone_ecmascript/livesearch',
        'search': '../../../../../../../buildout-cache/eggs/plone.app.search-1.0.4-py2.7.egg/plone/app/search/search',
        'select_all': '../../../../../../../buildout-cache/eggs/Products.CMFPlone-4.2.1.1-py2.7.egg/Products/CMFPlone/skins/plone_ecmascript/select_all',
        'dragdropreorder': '../../../../../../../buildout-cache/eggs/Products.CMFPlone-4.2.1.1-py2.7.egg/Products/CMFPlone/skins/plone_ecmascript/dragdropreorder',
        'collapsiblesections': '../../../../../../../buildout-cache/eggs/Products.CMFPlone-4.2.1.1-py2.7.egg/Products/CMFPlone/skins/plone_ecmascript/collapsiblesections',
        'form_tabbing': '../../../../../../../buildout-cache/eggs/Products.CMFPlone-4.2.1.1-py2.7.egg/Products/CMFPlone/skins/plone_ecmascript/form_tabbing',
        'popupforms': '../../../../../../../buildout-cache/eggs/Products.CMFPlone-4.2.1.1-py2.7.egg/Products/CMFPlone/skins/plone_ecmascript/popupforms',
        'jquery.highlightsearchterms': '../../../../../../../buildout-cache/eggs/Products.CMFPlone-4.2.1.1-py2.7.egg/Products/CMFPlone/skins/plone_ecmascript/jquery.highlightsearchterms',
        'first_input_focus': '../../../../../../../buildout-cache/eggs/Products.CMFPlone-4.2.1.1-py2.7.egg/Products/CMFPlone/skins/plone_ecmascript/first_input_focus',
        'accessibility': '../../../../../../../buildout-cache/eggs/Products.CMFPlone-4.2.1.1-py2.7.egg/Products/CMFPlone/skins/plone_ecmascript/accessibility',
        'styleswitcher': '../../../../../../../buildout-cache/eggs/Products.CMFPlone-4.2.1.1-py2.7.egg/Products/CMFPlone/skins/plone_ecmascript/styleswitcher',
        'toc': '../../../../../../../buildout-cache/eggs/Products.CMFPlone-4.2.1.1-py2.7.egg/Products/CMFPlone/skins/plone_ecmascript/toc',
        'collapsibleformfields': '../../../../../../../buildout-cache/eggs/Products.CMFPlone-4.2.1.1-py2.7.egg/Products/CMFPlone/skins/plone_ecmascript/collapsibleformfields',
        'comments': '../../../../../../../buildout-cache/eggs/plone.app.discussion-2.1.7-py2.7.egg/plone/app/discussion/browser/javascripts/comments',
        'dropdown': '../../../../../../../buildout-cache/eggs/Products.CMFPlone-4.2.1.1-py2.7.egg/Products/CMFPlone/skins/plone_ecmascript/dropdown',
        'table_sorter': '../../../../../../../buildout-cache/eggs/Products.CMFPlone-4.2.1.1-py2.7.egg/Products/CMFPlone/skins/plone_ecmascript/table_sorter',
        'calendar_formfield': '../../../../../../../buildout-cache/eggs/Products.CMFPlone-4.2.1.1-py2.7.egg/Products/CMFPlone/skins/plone_ecmascript/calendar_formfield',
        'formUnload': '../../../../../../../buildout-cache/eggs/Products.CMFPlone-4.2.1.1-py2.7.egg/Products/CMFPlone/skins/plone_ecmascript/formUnload',
        'formsubmithelpers': '../../../../../../../buildout-cache/eggs/Products.CMFPlone-4.2.1.1-py2.7.egg/Products/CMFPlone/skins/plone_ecmascript/formsubmithelpers',
        'unlockOnFormUnload': '../../../../../../../buildout-cache/eggs/Products.CMFPlone-4.2.1.1-py2.7.egg/Products/CMFPlone/skins/plone_ecmascript/unlockOnFormUnload',
        'autocomplete': '../../../../../../../buildout-cache/eggs/plone.formwidget.autocomplete-1.2.3-py2.7.egg/plone/formwidget/autocomplete/jquery-autocomplete/jquery.autocomplete.min',
        'formwidget-autocomplete': '../../../../../../../buildout-cache/eggs/plone.formwidget.autocomplete-1.2.3-py2.7.egg/plone/formwidget/autocomplete/jquery-autocomplete/formwidget-autocomplete',
        'contenttree': '../../../../../../../buildout-cache/eggs/plone.formwidget.contenttree-1.0.5-py2.7.egg/plone/formwidget/contenttree/jquery-contenttree/contenttree',
        'jquery_prettyPhoto': '../../../../../../../buildout-cache/eggs/collective.prettyphoto-0.4.5.2-py2.7.egg/collective/prettyphoto/browser/javascript/jquery.prettyPhoto',
        'prettyPhoto': 'empty:',
        'login': '../../../../../../../buildout-cache/eggs/Products.CMFPlone-4.2.1.1-py2.7.egg/Products/CMFPlone/skins/plone_ecmascript/login',
        'domready_script': 'js/scripts',
    },
    //modules: [                                                                       
        //{                                                                            
            //name: "build"                                                             
        //}                                                                            
    //]                                                                                
 })
