require.config({
    paths: {
        'modernizr':   'components/modernizr/modernizr',
        'bootstrap':   'components/bootstrap/docs/assets/js/bootstrap',
        'domReady':    'components/requirejs-domready/domReady',
        'hoverIntent': '/++resource++collective.collage.megamenu/jquery.hoverIntent.minified',
        'collage':     '/++resource++collage-resources/collage',
        'collage-patch': '/++resource++collective.collage.megamenu/collage-patch',
        'megamenu':    '/++resource++collective.collage.megamenu/megamenu',
        'jquery-integration': '/jquery-integration',
        'jquerytools': '/++resource++plone.app.jquerytools',
        'jquerytools-dateinput': '/++resource++plone.app.jquerytools.dateinput',
        'jquerytools-overlayhelpers': '/++resource++plone.app.jquerytools.overlayhelpers',
        'jquerytools-form': '/++resource++plone.app.jquerytools.form',
        'register-function': '/register_function',
        'plone_javascript_variables': '/plone_javascript_variables',
        'nodeutilities': '/nodeutilities',
        'cookie_functions': '/cookie_functions',
        'livesearch': '/livesearch',
        'search': '/++resource++search',
        'select_all': '/select_all',
        'dragdropreorder': '/dragdropreorder',
        'collapsiblesections': '/collapsiblesections',
        'form_tabbing': '/form_tabbing',
        'popupforms': '/popupforms',
        'jquery.highlightsearchterms': '/jquery.highlightsearchterms',
        'first_input_focus': '/first_input_focus',
        'accessibility': '/accessibility',
        'styleswitcher': '/styleswitcher',
        'toc': '/toc',
        'collapsibleformfields': '/collapsibleformfields',
        'comments': '/++resource++plone.app.discussion.javascripts/comments',
        'dropdown': '/dropdown',
        'table_sorter': '/table_sorter',
        'calendar_formfield': '/calendar_formfield',
        'formUnload': '/formUnload',
        'formsubmithelpers': '/formsubmithelpers',
        'unlockOnFormUnload': '/unlockOnFormUnload',
        'autocomplete': '/++resource++plone.formwidget.autocomplete/jquery.autocomplete.min',
        'formwidget-autocomplete': '/++resource++plone.formwidget.autocomplete/formwidget-autocomplete',
        'contenttree': '/++resource++plone.formwidget.contenttree/contenttree',
        'jquery_prettyPhoto': '/++resource++jquery.prettyPhoto',
        'prettyPhoto': '/prettyPhoto',
        'login': '/login',
        'domready_script': 'js/scripts',
      },

    shim: {
        'jquerytools-dateinput': ['jquerytools'],
        'jquerytools-overlayhelpers': ['jquerytools'],
        'jquerytools-form': ['jquerytools'],
        'search': ['modernizr','plone_javascript_variables'],
        'select_all': ['plone_javascript_variables'],
        'popupforms': ['jquerytools-overlayhelpers'],
        'accessibility': ['cookie_functions'],
        'styleswitcher': ['cookie_functions'],
        'formwidget-autocomplete': ['autocomplete'],
        'prettyPhoto': ['jquery_prettyPhoto'],
        'collage-patch': ['collage'],
        'hoverIntent': ['collage', 'collage-patch'],
        'megamenu': ['hoverIntent'],
        'login': ['register-function'],
        'domready_script': ['megamenu', 'domReady'],
    }
});
require([
    'domReady',
    'jquery-integration',
    'jquerytools',
    'jquerytools-dateinput',
    'jquerytools-overlayhelpers',
    'jquerytools-form',
    'register-function',
    'plone_javascript_variables',
    'nodeutilities',
    'cookie_functions',
    'livesearch',
    'search',
    'select_all',
    'dragdropreorder',
    'collapsiblesections',
    'form_tabbing',
    'popupforms',
    'jquery.highlightsearchterms',
    'first_input_focus',
    'accessibility',
    'styleswitcher',
    'toc',
    'collapsibleformfields',
    'comments',
    'dropdown',
    'table_sorter',
    'calendar_formfield',
    'formUnload', 
    'formsubmithelpers',
    'unlockOnFormUnload',
    'autocomplete',
    'formwidget-autocomplete',
    'contenttree',
    'jquery_prettyPhoto',
    'prettyPhoto',
    'collage',
    'collage-patch',
    'hoverIntent',
    'megamenu',
    'bootstrap',
    'login',
    'domready_script',
], function(domReady){
    domReady(function() {
    });
});
